<a href="https://colab.research.google.com/github/ftetteh/py/blob/main/pytorch_fundamentals_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals
Resource notebook:https://www.learnpytorch.io/00_pytorch_fundamentals/
if you have any question:https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [1]:
print("Hello I'm excited to learn PyTorch!")

Hello I'm excited to learn PyTorch!


In [1]:
!nvidia-smi

Fri Aug 18 15:07:26 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.0.1+cu118


In [3]:
## Introduction to Tensors

## Introduction to Tensors

### Creating Tensors
PyTorch tensors are created using 'torch.Tensor()' = https://pytorch.org/docs/stable/tensors.html

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
## a scalar has no dimensions is just a single number
scalar.ndim

0

In [4]:
# Get tensor back as a python int
scalar.item()

7

In [6]:
# Vector has more than one number, that is magnetude and direction
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
# checking the dimensions of 'vector'
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
MATRIX= torch.tensor([[1, 2],
                       [2, 4]])
MATRIX

tensor([[1, 2],
        [2, 4]])

In [13]:
MATRIX.ndim

2

In [14]:
# Getting MATRIX indexed on the zero axis
MATRIX[0]

tensor([1, 2])

In [16]:
# Getting MATRIX indexed on the first axis
MATRIX[1]

tensor([2, 4])

In [17]:
# getting the shape of MATRIX
MATRIX.shape

torch.Size([2, 2])

In [18]:
# TENSOR
TENSOR = torch.tensor(([[[1, 2, 3],
                         [2, 6, 9],
                         [2, 4, 5]]]))
TENSOR

tensor([[[1, 2, 3],
         [2, 6, 9],
         [2, 4, 5]]])

In [19]:
TENSOR.ndim

3

In [20]:
# The shpe of our TENSOR is a 1 dimension of a 3 by 3 tensor
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[1, 2, 3],
        [2, 6, 9],
        [2, 4, 5]])

In [23]:
TENSOR_2 = ([[[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9],
               [10, 11, 12]]]])
TENSOR_2

[[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]]

### Random tensors
Why random tensors?

Random tensors are important because of the way many neural netwoks learn is that they start with tensors full of random numbers then adjust those random numbers to better represent the data.

'Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers'

Torch random tensors-https://pytorch.org/docs/stable/generated/torch.rand.html

In [28]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4519, 0.7522, 0.6953, 0.8396],
        [0.8404, 0.0160, 0.1595, 0.3986],
        [0.3065, 0.8660, 0.5506, 0.1591]])

In [30]:
random_tensor.ndim

2

In [31]:
random_tensor = torch.rand(10, 10)
random_tensor

tensor([[0.3444, 0.2066, 0.9307, 0.2196, 0.4701, 0.6400, 0.3305, 0.2429, 0.4849,
         0.8950],
        [0.2674, 0.3390, 0.4912, 0.0572, 0.0609, 0.4690, 0.4483, 0.3918, 0.1324,
         0.5801],
        [0.3839, 0.3114, 0.3602, 0.5570, 0.6825, 0.8761, 0.8599, 0.9887, 0.8921,
         0.0216],
        [0.3946, 0.6455, 0.7180, 0.3982, 0.7255, 0.5583, 0.2205, 0.7363, 0.1872,
         0.3888],
        [0.6790, 0.1150, 0.9484, 0.2263, 0.6207, 0.2559, 0.9328, 0.4500, 0.5652,
         0.5003],
        [0.5992, 0.4088, 0.0639, 0.8217, 0.3821, 0.0103, 0.6224, 0.4754, 0.6247,
         0.7368],
        [0.3358, 0.9196, 0.1045, 0.8771, 0.5602, 0.0634, 0.2800, 0.4112, 0.6289,
         0.9130],
        [0.8866, 0.3040, 0.8110, 0.0162, 0.7514, 0.2451, 0.5388, 0.1654, 0.9828,
         0.0667],
        [0.7884, 0.5286, 0.2550, 0.7805, 0.0999, 0.4281, 0.5254, 0.9239, 0.9821,
         0.3845],
        [0.3644, 0.1707, 0.9356, 0.0372, 0.3780, 0.1734, 0.2599, 0.0392, 0.9601,
         0.7275]])

In [33]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224))    #  color channels (red, green, blue), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [34]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(5, 10, 10))    #  color channels (red, green, blue), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([5, 10, 10]), 3)

### Zeros and ones

In [35]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [4]:
#  Create a tensor of all ones
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [5]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like


In [6]:
# Use torch.range()
torch.range(0, 10)

<ipython-input-6-74fde6f68c60>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [10]:
# Use torch.range()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
# Use torch.range() and get deprecated message, use torch.arrange()
zero_to_thousand = torch.arange(start=0, end=1000, step=50)
zero_to_thousand

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [12]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
torch.__version__

'2.0.1+cu118'

### Tensor datatype

In [13]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None )
float_32_tensor

tensor([3., 6., 9.])

In [14]:
float_32_tensor.dtype

torch.float32

In [16]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16 )
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [23]:
float_32_tensor.dtype

torch.float32

In [5]:
# Float 32 Tensor
float_32_tensor= torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device is your tensor on
                              requires_grad=False ) # whether or not to track gradients with thitensors operations
float_32_tensor

tensor([3., 6., 9.])

In [6]:
# Create float 16 tensor using the float 32 tensor created
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [7]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [11]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [12]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensor attributes
1. Tensor not right dtype - to get the datatype from a tensor, we can use 'tensor.dtype'
2. Tensor not right shape - to get the shape from a tensor, we can use 'tensor.shape'
3. Tensor not on the right Device - to get device from a gtensor, we can use tensor.device.

---



In [13]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8726, 0.6132, 0.8887, 0.3794],
        [0.3566, 0.8223, 0.5113, 0.1161],
        [0.1806, 0.2241, 0.7499, 0.8615]])

In [15]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.8726, 0.6132, 0.8887, 0.3794],
        [0.3566, 0.8223, 0.5113, 0.1161],
        [0.1806, 0.2241, 0.7499, 0.8615]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (Tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [16]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
# add number to tensor
tensor + 10

tensor([11, 12, 13])

In [17]:
# Multiply by 10
tensor * 10


tensor([10, 20, 30])

In [18]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [19]:
# Using PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [20]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix multiplication
Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)
More information on multiplying matrices: https://www.mathsisfun.com/algebra/matrix-multiplying.html


In [22]:
# Element wise multiplicatio
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])
